#!/bin/sh

type="jpg"

urxvtd -q -o -f

xset +fp ~/.fonts                                &
xset fp rehash                                   &

xsetroot -name "$(hostname -s)"                  &
xsetroot -cursor_name left_ptr                   &

xrdb ~/.Xresources                               &

hsetroot -fill .wmconf/wallpapers/current.$type  &

. .wmconf/scripts/dwm
